#custom your user, password database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.url=jdbc:mysql://root:ru5SyvQiQ8jwqb0mjfri@containers-us-west-175.railway.app:7735/railway
spring.datasource.username=root
spring.datasource.password=ru5SyvQiQ8jwqb0mjfri

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql = false

#JWT
jwt.header=Authorization
jwt.base64-secret=ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
jwt.expiration=604800
jwt.token-validity-in-seconds-for-remember-me = 108000
jwt.route.authentication.path=/auth
jwt.route.authentication.refresh=/refresh


#custom your port
server.port=8090
#disable after Dev phase
#server.error.include-stacktrace=always

#mail properties
email.username = asd.skyer3@gmail.com
email.password = rexzgwhchsnufsjm

#Oauth2 configure(use your id, secret api)
spring.security.oauth2.client.registration.google.client-id= 122193712863-ulr2q0cpf13q03mbnrbhdck2dkvtq7bh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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
spring.main.allow-circular-references=true

#multiPartFile size config
spring.servlet.multipart.max-file-size = -1
spring.servlet.multipart.max-request-size = -1

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS = false